# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# Synopsis: Configuration for PSRule.Rules.CAF
apiVersion: github.com/microsoft/PSRule/v1
kind: ModuleConfig
metadata:
  name: PSRule.Rules.CAF
spec:
  binding:
    targetType:
    - 'ResourceType'
    - 'Type'
    targetName:
    - 'ResourceName'
    - 'Name'
    field:
      resourceId: [ 'ResourceId' ]
      subscriptionId: [ 'SubscriptionId' ]
      resourceGroupName: [ 'ResourceGroupName' ]
  rule:
    baseline: 'CAF.Strict'
